### ISSUE TITLE
error in preprocessor

### ISSUE THREAD

**Issue by gnniaaa** [merantix/imitation-learning#21]
When I run the preprocessor.py by python imitation/preprocessor.py --preproc_config_paths=config-preprocess-production.yaml
I got this error:tensorflow.python.framework.errors_impl.NotFoundError: /home/ps/tmp/imitation-learning/config-preprocess-production.yaml; No such file or directory
What does this mean?

**Comment by markus-hinsche** [comment]
Does `python imitation/preprocessor.py --preproc_config_paths=imitation/config-preprocess-production.yaml` work?

**Comment by gnniaaa** [comment]
Yes！Thank you！
